#!/bin/bash

echo "🔍 DIAGNÓSTICO AZURE STATIC WEB APPS"
echo "================================="

echo ""
echo "📋 Información del Proyecto:"
echo "- Repo: Front-Antivirus"
echo "- App esperada: lively-moss-07487241e"
echo "- URL esperada: https://lively-moss-07487241e.1.azurestaticapps.net/"

echo ""
echo "🔧 PASOS PARA RESOLVER EL TOKEN:"
echo ""
echo "1. Ve a Azure Portal: https://portal.azure.com"
echo "2. Busca tu Static Web App en 'All resources'"
echo "3. Si no existe, créala nueva con estos datos:"
echo "   - Name: lively-moss-07487241e (o cualquier nombre)"
echo "   - Resource Group: nuevo o existente"
echo "   - GitHub Integration: Conectar a este repo"
echo ""
echo "4. Una vez en la Static Web App:"
echo "   - Ve a 'Overview'"
echo "   - Haz clic en 'Manage deployment token'"
echo "   - Copia el token completo"
echo ""
echo "5. En GitHub:"
echo "   - Repo → Settings → Secrets and variables → Actions"
echo "   - Actualiza: AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_MOSS_07487241E"
echo "   - Pega el nuevo token"

echo ""
echo "🚀 ALTERNATIVA RÁPIDA - GitHub Pages:"
echo ""
echo "1. Ejecutar: git checkout -b backup-deploy"
echo "2. Ejecutar: git push origin backup-deploy"
echo "3. La app se desplegará en GitHub Pages automáticamente"

echo ""
echo "📊 Estado actual del build:"
ls -la build/client/ 2>/dev/null && echo "✅ Build exists" || echo "❌ Build missing - run 'npm run build'"

echo ""
echo "🔗 Enlaces útiles:"
echo "- Azure Portal: https://portal.azure.com"
echo "- Documentación: https://docs.microsoft.com/en-us/azure/static-web-apps/"
echo "- GitHub Secrets: https://github.com/$(git config --get remote.origin.url | sed 's/.*github.com[:/]\([^/]*\/[^/]*\).*/\1/' | sed 's/\.git$//')/settings/secrets/actions"
