name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci

      - name: Build project
        run: |
          npm run build

      - name: Prepare clean deployment
        run: |
          # PASO CRÍTICO: Ocultar package.json temporalmente para evitar detección de Node.js
          mv package.json package.json.backup
          mv node_modules node_modules.backup || true
          
          # Crear directorio completamente limpio
          rm -rf static-deploy
          mkdir static-deploy
          
          # Copiar SOLO archivos estáticos
          cp -r build/client/* static-deploy/
          cp staticwebapp.config.json static-deploy/
          touch static-deploy/.nojekyll
          
          # Crear un archivo que indique que es HTML estático
          echo "<!DOCTYPE html><html><head><meta http-equiv='refresh' content='0;url=index.html'></head></html>" > static-deploy/default.htm
          
          # Verificar que NO hay archivos Node.js
          echo "=== Verificando directorio limpio ==="
          ls -la static-deploy/ | grep -E "(package\.json|node_modules|\.js$)" || echo "✅ No Node.js files detected"
          
          echo "=== Root directory (should not show package.json) ==="
          ls -la . | grep package || echo "✅ No package.json in root during deploy"
          
          echo "=== Static deploy contents ==="
          ls -la static-deploy/
          test -f static-deploy/index.html && echo "✅ index.html exists" || echo "❌ index.html missing"

      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_MOSS_07487241E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "static-deploy"
          api_location: ""
          output_location: ""
          skip_app_build: true
          skip_api_build: true

      - name: Restore files after deploy
        if: always()
        run: |
          # Restaurar archivos originales
          mv package.json.backup package.json || true
          mv node_modules.backup node_modules || true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_LIVELY_MOSS_07487241E }}
          action: "close"
