name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm ci

      - name: Build project
        run: |
          npm run build
          
      - name: Prepare deployment files
        run: |
          # Limpiar y crear directorio de deploy
          rm -rf deploy
          mkdir -p deploy
          
          # Copiar solo los archivos necesarios
          cp -r build/client/* deploy/
          cp staticwebapp.config.json deploy/
          
          # Crear archivos que eviten que Oryx detecte esto como proyecto Node.js
          touch deploy/.nojekyll
          rm -f deploy/package.json || true
          
          # Crear un archivo web.config para IIS si es necesario
          echo '<?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <rewrite>
                <rules>
                  <rule name="React Routes" stopProcessing="true">
                    <match url=".*" />
                    <conditions logicalGrouping="MatchAll">
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                      <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="/index.html" />
                  </rule>
                </rules>
              </rewrite>
            </system.webServer>
          </configuration>' > deploy/web.config
          
          # Verificar contenido
          echo "=== Deploy directory contents ==="
          ls -la deploy/
          echo "=== Checking key files ==="
          test -f deploy/index.html && echo "✅ index.html exists" || echo "❌ index.html missing"
          test -f deploy/staticwebapp.config.json && echo "✅ staticwebapp.config.json exists" || echo "❌ staticwebapp.config.json missing"

      - name: Deploy to Azure Static Web Apps
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_OCEAN_07D3E3A1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          ###### Repository/Build Configurations ######
          app_location: "/deploy"
          api_location: ""
          output_location: ""
          ###### Advanced settings ######
          skip_app_build: true
          skip_api_build: true
        env:
          # Deshabilitar detección automática de Oryx
          DISABLE_STATIC_SITE_BUILD: true
          PRE_BUILD_COMMAND: "echo 'Skipping pre-build'"
          CUSTOM_BUILD_COMMAND: "echo 'Using pre-built files'"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_POLITE_OCEAN_07D3E3A1E }}
          action: "close"
