name: Deploy to GitHub Pages (Backup)

on:
  workflow_dispatch: # Manual trigger
  push:
    branches: [backup-deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install and Build
        run: |
          npm ci
          npm run build

      - name: Prepare for GitHub Pages
        run: |
          cp -r build/client/* ./
          echo "frontend-antivirus.github.io" > CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          cname: frontend-antivirus.github.io
